### PR TITLE
Update for bullseye

### PR DESCRIPTION
**Pull request by sopelj**

### CODE REVIEW

**Comment by sopelj** [comment]
recheck (see if job is available)

**Comment by sopelj** [comment]
recheck

**Comment by jfbourque** [comment]
recheck

**Comment by sopelj** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by sopelj** [comment]
recheck

**Comment by sopelj** [comment]
recheck

**Comment by sopelj** [comment]
recheck

**Comment by sopelj** [comment]
recheck (added indices to database)

**Comment by sopelj** [comment]
recheck (timed out, and branches updated)

**Comment by sopelj** [comment]
recheck (still timing out. updated branches with master)

**Comment by sopelj** [comment]
recheck

**Comment by sopelj** [comment]
recheck

**Pull request merged**
