### PR TITLE
context: fixes for autogenerated name

### PR DESCRIPTION
**Pull request by bloom1**
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/233
Depends-On: https://github.com/wazo-platform/wazo-confd/pull/404
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/210

### CODE REVIEW

**Comment by bloom1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by bloom1** [comment]
recheck

**Comment by bloom1** [comment]
recheck

**Comment by fblackburn1** [comment]
regate

**Comment by fblackburn1** [comment]
regate (check was done during merge of another PR)

**Comment by fblackburn1** [comment]
fail is unrelated to this branch
master branch is broken for now, so we must wait until it's fixed

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
manually merged because issue was related to another PR (merged juste before gating)
Having this PR in master will help to debug

**Pull request merged**
