### PR TITLE
add and improve provisioning tests

### PR DESCRIPTION
**Pull request by fblackburn1**
Depends-on: https://github.com/wazo-platform/wazo-provd/pull/86
Depends-on: https://github.com/wazo-platform/xivo-config/pull/92
Depends-on: https://github.com/wazo-platform/wazo-confgend/pull/96

### CODE REVIEW

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck (issue with provd-plugins, now fixed)

**Comment by fblackburn1** [comment]
Recheck (fix pushed to provd)

**Comment by bloom1** [comment]
recheck

**Review by bloom1 — APPROVED** [review]

**Comment by fblackburn1** [comment]
Regate

**Pull request merged**
