### PR TITLE
debug random failures

### PR DESCRIPTION
**Pull request by fblackburn1**
Depends-on: https://github.com/wazo-platform/wazo-sysconfd/pull/64

### CODE REVIEW

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by sopelj** [comment]
recheck

**Comment by sopelj** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
Not needed anymore. Fixed by https://github.com/wazo-platform/wazo-sysconfd/pull/65

**Pull request closed without merging**
