### PR TITLE
Wp 554 mobile keeps ringing

### PR DESCRIPTION
**Pull request by pc-m**
Depends-On: https://github.com/wazo-platform/wazo-calld/pull/218
Depends-On: https://github.com/wazo-platform/xivo-bus/pull/53

### CODE REVIEW

**Review by sduthil — APPROVED** [review]

**Comment by sduthil** [comment]
AFAIU, those scenarios do not create a refresh token, while the `push_notification_cancel` event is only sent when a refresh token of type `mobile` is created. Did I miss something?

**Comment by sduthil** [comment]
recheck

**Comment by pc-m** [comment]
> AFAIU, those scenarios do not create a refresh token, while the `push_notification_cancel` event is only sent when a refresh token of type `mobile` is created. Did I miss something?

WTF... You're right, neither the push or the push cancel should be sent without a mobile refresh token. I'll dig into this to understand how this could work

**Comment by pc-m** [comment]
> > AFAIU, those scenarios do not create a refresh token, while the `push_notification_cancel` event is only sent when a refresh token of type `mobile` is created. Did I miss something?
> 
> WTF... You're right, neither the push or the push cancel should be sent without a mobile refresh token. I'll dig into this to understand how this could work



> > AFAIU, those scenarios do not create a refresh token, while the `push_notification_cancel` event is only sent when a refresh token of type `mobile` is created. Did I miss something?
> 
> WTF... You're right, neither the push or the push cancel should be sent without a mobile refresh token. I'll dig into this to understand how this could work

ah the push is sent on a mobile refresh token OR a mobile session

**Comment by pc-m** [comment]
> > ah the push is sent on a mobile refresh token OR a mobile session
> 
> Ah thanks, that explains why. Do you think we should change the scenarios to use a refresh token?

I think I will duplicate the tests to cover both scenarios

**Comment by fblackburn1** [comment]
recheck

**Comment by sduthil** [comment]
recheck

**Review by sduthil — APPROVED** [review]

**Pull request merged**
