### PR TITLE
call filters: test with multiple lines

### PR DESCRIPTION
**Pull request by sduthil**
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/176
Depends-On: https://github.com/wazo-platform/wazo-agid/pull/93

### CODE REVIEW

**Comment by sduthil** [comment]
recheck

**Comment by sduthil** [comment]
recheck

**Comment by sduthil** [comment]
recheck

**Comment by sduthil** [comment]
recheck

**Comment by sduthil** [comment]
recheck

**Comment by sduthil** [comment]
recheck

**Comment by sduthil** [comment]
recheck

**Comment by sduthil** [comment]
recheck

**Comment by sduthil** [comment]
AFAIK, the failing tests in acceptance are not related to this branch content

**Comment by bloom1** [comment]
recheck

**Comment by bloom1** [comment]
recheck

**Comment by sduthil** [comment]
recheck

**Review by bloom1 — APPROVED** [review]
Finally Zuul got its fingers out of its nose :smiley:

**Comment by bloom1** [comment]
regate

**Comment by sduthil** [comment]
merging anyway: the failure has nothing to do with this code.

**Pull request merged**
