### PR TITLE
Wazo 1249 user presence hold

### PR DESCRIPTION
**Pull request by fblackburn1**
Depends-on: https://github.com/wazo-platform/pylinphonelib/pull/9

### CODE REVIEW

**Comment by fblackburn1** [comment]
recheck

**Comment by bloom1** [comment]
recheck

**Comment by bloom1** [comment]
regate

**Comment by bloom1** [comment]
regate

**Comment by fredericlepied** [comment]
regate

**Comment by bloom1** [comment]
regate

**Comment by fblackburn1** [comment]
regate

**Pull request merged**
