### PR TITLE
install french sound files

### PR DESCRIPTION
**Pull request by pc-m**

### CODE REVIEW

**Comment by pc-m** [comment]
recheck

**Comment by pc-m** [comment]
Please do not merge this PR until it gets executed because I do not have the appropriate setup to run wizard tests locally

**Comment by pc-m** [comment]
recheck

**Comment by pc-m** [comment]
> Build failed.
> 
> * [wazo-acceptance ](https://zuul.wazo.community/zuul/t/local/build/405d4e936e0b4fd4b08e4588900f84ae) : FAILURE in 1h 22m 51s

I've added some QueueStatus polling when we create a queue to avoid the `Queue not found` errors in the Asterisk log

**Review by fblackburn1 — DISMISSED** [review]

**Review by fblackburn1 — COMMENTED** [review]
I'll help you to debug this race condition in 2 weeks :)

**Review by fblackburn1 — APPROVED** [review]

**Pull request merged**
