### PR TITLE
Add sngrep helper and log to files for each scenario

### PR DESCRIPTION
**Pull request by sopelj**
Depends-on: https://github.com/wazo-platform/pylinphonelib/pull/16

### CODE REVIEW

**Comment by jfbourque** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
Still apparmor issue - in progress to be solved on zuul by @jfbourque

**Comment by fblackburn1** [comment]
recheck

**Review by fblackburn1 — CHANGES_REQUESTED** [review]
in some case (mostly all?) sngrep is not correctly stopped
In the last zuul run:
* scenario: `Check that the wazo server has a uuid`
  * have a pcap of 4.8MB 
When you open the pcap, it's seem that sngrep ran during all tests

**Comment by fblackburn1** [comment]
recheck (depends-on added on first post)

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck (add carriage return in pylinphonelib)

**Comment by fblackburn1** [comment]
recheck (use a lot of buffer)

**Comment by fblackburn1** [comment]
recheck (add debug to linphonelib)

**Comment by fblackburn1** [comment]
recheck

**Pull request merged**
