### PR TITLE
Pull request for automate-x-468-automate-agent-penalty

### PR DESCRIPTION
**Pull request by fblackburn1**
automate x-438 agent penalty
remove useless sleep
extract register_and_track_phone to helper
attended transfer: use linphone instead of chan_test
automate x-164 attended transfer

### CODE REVIEW

**Comment by fredericlepied** [comment]
recheck

**Comment by fblackburn1** [comment]
woups didn't see you have already approve the PR
Well a force push to fix a typo with the following diff
```diff
-    Given agent "1801" is logged
     Given agent "1802" is logged
+    Given agent "1803" is logged
```

**Comment by fblackburn1** [comment]
Depends-on: https://github.com/wazo-platform/wazo-acceptance/pull/79

**Comment by fblackburn1** [comment]
post-merge action: remove test from testlink if you find it equivalent

**Pull request merged**
