### PR TITLE
improve README.md

### PR DESCRIPTION
**Pull request by fredericlepied**
Depends-On: https://github.com/wazo-platform/sf-jobs/pull/46
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/28

### CODE REVIEW

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
:rofl: I'm a witcher

**Comment by fblackburn1** [comment]
I did not notice that it was a PR to test `Depends-on` with manage-db. I am right? or we can mergeit?

**Comment by fredericlepied** [comment]
> I did not notice that it was a PR to test `Depends-on` with manage-db. I am right? or we can mergeit?

yes it was for testing but the improvment to the doc is still valid so we could merge it if we find it useful.

**Pull request merged**
