### PR TITLE
Zuul migration

### PR DESCRIPTION
**Pull request by rgarrigue**

### CODE REVIEW

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by fblackburn1** [comment]
@rgarrigue all tests pass, here's the new error
```
2021-04-22 19:16:32.041103 | TASK [Upload configuration]
2021-04-22 19:16:44.425809 | vm-debian-10-m1m | ERROR
2021-04-22 19:16:44.450984 | vm-debian-10-m1m | {
2021-04-22 19:16:44.451071 | vm-debian-10-m1m |   "msg": "symlink has no referent: \"/etc/mail/smrsh/mail.local\"\nrsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1651) [generator=3.1.2]\n",
2021-04-22 19:16:44.451126 | vm-debian-10-m1m |   "rc": 23
2021-04-22 19:16:44.451175 | vm-debian-10-m1m | }
```

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
regate

**Pull request merged**
