### PR TITLE
Add condition for sngrep

### PR DESCRIPTION
**Pull request by sopelj**

### CODE REVIEW

**Review by fblackburn1 — CHANGES_REQUESTED** [review]
All helpers/attributes are available in the `context` object
They are in `context.instances.<config-name>.<attr> but to simplify usage, the `default` config-name is also at the root of `context`
ex:
`context.instances.default.helpers` == `context.helpers`
`context.instances.default.confd_client` == `context.confd_client`

so to access to helpers from another instance, you must use `context.instances.xxx`
ref: https://github.com/wazo-platform/wazo-acceptance/blob/master/wazo_acceptance/environment.py#L59-L72

I don't have objection to no implement sngrep on non-default instance.
But the last commit should not stand that helpers are not available

**nitpicking**
* Can you try to always add the `why` to your commit. ex: the first commit, you describe the commit, but not why you do it. I think it's styling issue, but it may fix something too ?
* For next commits, can you try to split typing from other modification. It will help transition (it doesn't hurt for this commit, but I want to prevent :sweat_smile: )

**Comment by sopelj** [comment]
> All helpers/attributes are available in the `context` object They are in `context.instances.<config-name>.<attr>` but to simplify usage, the `default` config-name is also at the root of `context` ex: `context.instances.default.helpers` == `context.helpers` `context.instances.default.confd_client` == `context.confd_client`
> 
> so to access to helpers from another instance, you must use `context.instances.xxx.helpers` ref: https://github.com/wazo-platform/wazo-acceptance/blob/master/wazo_acceptance/environment.py#L59-L72
> 
> I don't have objection to no implement sngrep on non-default instance. But the last commit should not stand that helpers are not available
> 
> Small notices
> 
> * Can you try to always add the `why` to your commit. ex: the first commit, you describe the commit, but not why you do it. I think it's styling issue, but it may fix something too ?
> * For next commits, can you try to split typing from other modification. It will help transition (it doesn't hurt for this commit, but I want to prevent sweat_smile )

Ok, I thought that might be the case, but it was unclear. Hence the minimal typing, which was an attempt to understand. However, it didn't really help, since it was localized.

So do you want me to just change the text in the commit or do you want me to run sngrep on both?

I did try to split the commits, that's why there are two. :P Although, there was so little typing I didn't think it was worth undoing everything, commiting part, and then putting it back. But I did hold back on typing. Would have loved to add more.

I mean, I did say why ("It is not available on secondary instance in ha tests"), although, as you pointed out my reasoning was incorrect, and I'll change that. Our commits do frequently lack that information, sadly.

**Comment by fblackburn1** [comment]
> Ok, I thought that might be the case, but it was unclear. Hence the minimal typing, which was an attempt to understand. However, it didn't really help, since it was localized.
> 
> So do you want me to just change the text in the commit or do you want me to run sngrep on both?

As I said, I don't have objection to limit the scope to only default instance. It was initially to debug non-ha test ;)
Feel free to implement it or not (and only changing the text)
 
> 
> I did try to split the commits, that's why there are two. :P Although, there was so little typing I didn't think it was worth undoing everything, commiting part, and then putting it back. But I did hold back on typing. Would have loved to add more.

Yep, as I said, this commit didn't hurt. Only to be clear for next time :)

> 
> I mean, I did say why ("It is not available on secondary instance in ha tests"), although, as you pointed out my reasoning was incorrect, and I'll change that.

My bad, I talked about your **second** commit, not the first :sweat_smile: . 
```
Directly call use_context_with_mode instead of calling private method.
Also use setattr instead of manually calling the dunder method
```
>  Our commits do frequently lack that information, sadly.

Yep we must force us to always add this info :)

**Comment by sopelj** [comment]
> > Ok, I thought that might be the case, but it was unclear. Hence the minimal typing, which was an attempt to understand. However, it didn't really help, since it was localized.
> > So do you want me to just change the text in the commit or do you want me to run sngrep on both?
> 
> As I said, I don't have objection to limit the scope to only default instance. It was initially to debug non-ha test wink Feel free to implement it or not (and only changing the text)

Ok, thanks. I just wanted to check. I update the commit.

> > I did try to split the commits, that's why there are two. :P Although, there was so little typing I didn't think it was worth undoing everything, commiting part, and then putting it back. But I did hold back on typing. Would have loved to add more.
> 
> Yep, as I said, this commit didn't hurt. Only to be clear for next time smile

Oh OK. That makes sense, just I hear this usually when "this time is OK", so I'm just checking if it's actually OK. haha. 

> > I mean, I did say why ("It is not available on secondary instance in ha tests"), although, as you pointed out my reasoning was incorrect, and I'll change that.
> 
> My bad, I talked about your **second** commit, not the first sweat_smile . I would like to know if it caused issue or it was only for styling / good practice
> 
> ```
> Directly call use_context_with_mode instead of calling private method.
> Also use setattr instead of manually calling the dunder method
> ```

Ah yes, sorry. It is indeed simply for good practices. I saw what the method did internally when trying to understand the code and I thought it would be better if we did it explicitly instead of calling their private method. It was mostly unrelated as with the dunder call. That's why I placed them in a separate commit.

> > Our commits do frequently lack that information, sadly.
> 
> Yep we must force us to always add this info smiley

For sure. Thanks for the reminder, I'll try and keep that in mind.

**Review by fblackburn1 — APPROVED** [review]

**Pull request merged**
