### PR TITLE
DO NOT MERGE: test PR websocketd

### PR DESCRIPTION
**Pull request by sopelj**
Depends-on: https://github.com/wazo-platform/wazo-websocketd/pull/71

### CODE REVIEW

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
Recheck

**Comment by fblackburn1** [comment]
recheck (remove other gardbage from websocketd PR to be sure it's only the commented logger setup is faulty)

**Comment by fblackburn1** [comment]
Recheck

**Comment by fblackburn1** [comment]
Recheck

**Comment by ja0x** [comment]
recheck

**Comment by ja0x** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck (to confirm previous result)

**Comment by fblackburn1** [comment]
recheck (branch has been force pushed for styling issue)

**Pull request closed without merging**
