### PR TITLE
WAZO-2413: add group DND test

### PR DESCRIPTION
**Pull request by bloom1**
Depends-On: https://github.com/wazo-platform/wazo-calld/pull/184
Depends-On: https://github.com/wazo-platform/wazo-auth-keys/pull/52

### CODE REVIEW

**Comment by bloom1** [comment]
recheck

**Comment by bloom1** [comment]
recheck

**Comment by bloom1** [comment]
recheck

**Comment by bloom1** [comment]
recheck

**Review by pc-m — APPROVED** [review]

**Comment by fblackburn1** [comment]
regate

**Pull request merged**
