### PR TITLE
provisioning: test HTTPS provisioning

### PR DESCRIPTION
**Pull request by sduthil**
Depends-On: https://github.com/wazo-platform/wazo-provd/pull/84

### CODE REVIEW

**Comment by fblackburn1** [comment]
Depends-on: https://github.com/wazo-platform/wazo-provd/pull/84

**Comment by sduthil** [comment]
recheck

**Comment by sduthil** [comment]
recheck

**Comment by bloom1** [comment]
recheck

**Review by bloom1 — APPROVED** [review]

**Pull request merged**
