### PR TITLE
Pull request for automate-x-164-attended-transfer

### PR DESCRIPTION
**Pull request by fblackburn1**
WIP

We need to find a way how to detect if chan_test is on hold or not.
I've not found value with amid or calld to have this information
We probably need to implement this feature in chan_test or do not use chan_test

Depends-on: https://github.com/wazo-platform/wazo-acceptance/pull/62

### CODE REVIEW

**Comment by fblackburn1** [comment]
@pc-m tell me what do you think about to use linphone for incoming call as implemented in this PR?
Should we try to replace all incoming call with this new step instead of using chan_test?

**Comment by pc-m** [comment]
> @pc-m tell me what do you think about using linphone for incoming call as implemented in this PR?
> Should we try to replace all incoming call with this new step instead of using chan_test?

I think it clear and does not add too much code above what we already use.
I would not make replacing chan_test with linphone my priority but I would not mind seeing it go. :stuck_out_tongue:

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Pull request merged**
