### PR TITLE
DO NOT MERGE: test pylinphone

### PR DESCRIPTION
**Pull request by fblackburn1**
Trigger https://github.com/wazo-platform/pylinphonelib/pull/21

### CODE REVIEW

**Comment by fblackburn1** [comment]
recheck (pylinphonelib branch has been updated to use bullseye container)

**Comment by sduthil** [comment]
@fblackburn1 can we close this PR, or is it still useful?

**Comment by fblackburn1** [comment]
@sduthil The PR has been updated to test https://github.com/wazo-platform/pylinphonelib/pull/21
until @sopelj (or someone else) have time to fix it, we need it

**Comment by fblackburn1** [comment]
recheck (fixed image has been pushed)

**Comment by fblackburn1** [comment]
Closing PR since everything is fine and pylinphone PR is merged

**Pull request closed without merging**
