### PR TITLE
Pull request for WAZO-2056-queuelog-tests

### PR DESCRIPTION
**Pull request by sduthil**
## rename asset for counting queuelog queue events

Why:

* better difference with counting agent events

## rename statcenter.feature to integration-asterisk-queuelog.feature

Why:

* Those tests are more integration tests for Asterisk than complete
acceptance tests.
* Unfortunately our test framework around Asterisk is
not good enough for those scenarios, so they can run in wazo-acceptance

## steps: add missing prefix to function names

Why:

* Abide by Style Guide (STYLEGUIDE.md)

### CODE REVIEW

**Comment by pc-m** [comment]
I think the tests should go one step further and test the HTTP interface, not the queue_log table.

**Comment by sduthil** [comment]
I agree, because it's what acceptance tests are for.

However, testing all test cases that way is redundant with wazo-call-logd integration tests, that already insert queue_log entries and test the stat aggregation logic. The tests of this PR would better go into an Asterisk integation test, coupled with a few "real" acceptance tests that would test the whole chain phone -> asterisk -> queue_log -> wazo-stat -> call-logd HTTP.

I did not go there because we don't have the framework for Asterisk integration tests with calls and agents outside of acceptance.

Proposition: move the tests of this PR into a `integration-asterisk.feature` file, and add 1-2 acceptance tests verifying the HTTP output of wazo-call-logd after a few calls. Do you have a better proposition?

**Comment by fblackburn1** [comment]
I like the proposition
* If you go ahead with it, please add a new STYLEGUIDE rule with something about integration test should start with the name `integration-*`

About the PR
* If you want to remove double quote around the waiting step, please update STYLEGUIDE to add an exception for interger value. Integer should always treated as variable

**Comment by sduthil** [comment]
> Yep a talk about the file no one read, but so useful to justify nitpicking smile

Not true, I'm glad to have a style guide to read when I'm wondering about where I should write my piece of code!

**Review by pc-m — APPROVED** [review]

**Pull request merged**
