### PR TITLE
Pull request for WAZO-1289-linphone-daemon

### PR DESCRIPTION
**Pull request by fblackburn1**
remove unused ringback tone status
sip_phone: rename hook status to call status
fix format string typo
queue: fix hangup step
phone_call: add missing steps
unarchive queue

### CODE REVIEW

**Comment by fblackburn1** [comment]
> The README still says to `apt install linphone-nogtk`; it's missing the steps to actually use the new linphone docker. Maybe it should also be automated? Or am I missing something?

Yeah you right, I wasn't supposed to put this branch into review at the first, but is really difficult to test linphone without :sweat_smile: 
I will fix it monday morning :)

**Comment by fblackburn1** [comment]
In fact, it is still missing the modification of zuul job to use (pull) linphone with docker

**Comment by fblackburn1** [comment]
recheck

**Comment by bloom1** [comment]
recheck

**Pull request merged**
